/*
=========================================
ZEPT0 DATA CLEANING
=========================================
Objective:
1. Understand dataset structure
2. Check for NULL values
3. Check duplicate records
4. Investigate products belonging to multiple categories
5. Standardize price columns
=========================================
*/
--Q1.Total Number of Records

SELECT COUNT(*) FROM ZEPTO

--Q2.VIEWING TABLE STRUCTURE

SELECT TOP 10 * FROM ZEPTO

--Q3.CHECKING NULL VALUES

SELECT SUM(CASE WHEN SKU_ID IS NULL THEN 1 ELSE 0 END) AS NULL_SKU_ID,
SUM(CASE WHEN CATEGORY IS NULL THEN 1 ELSE 0 END) AS NULL_CATEGORY,
SUM(CASE WHEN NAME IS NULL THEN 1 ELSE 0 END) AS NULL_NAME,
SUM(CASE WHEN MRP IS NULL THEN 1 ELSE 0 END) AS NULL_MRP,
SUM(CASE WHEN discountedSellingPrice IS NULL THEN 1 ELSE 0 END) AS NULL_DISOCUNT,
SUM(CASE WHEN availableQuantity IS NULL THEN 1 ELSE 0 END) AS NULL_AVAILABLEQUANTITY,
SUM(CASE WHEN discountedSellingPrice IS NULL THEN 1 ELSE 0 END) AS NULL_SELLINGPRICE,
SUM(CASE WHEN weightInGms IS NULL THEN 1 ELSE 0 END) AS NULL_WEIGHT,
SUM(CASE WHEN outOfStock IS NULL THEN 1 ELSE 0 END) AS NULL_STOCK,
SUM(CASE WHEN quantity IS NULL THEN 1 ELSE 0 END) AS NULL_QUANTITY
FROM ZEPTO

--Q4.FINDING DUPLICATE PRODUCT NAMES

SELECT NAME,COUNT(*) AS [COUNT] FROM ZEPTO
GROUP BY NAME
HAVING COUNT(*) > 1
ORDER BY [COUNT] DESC

--Q5.FINDING PRODUCTS APPERAING IN MULTIPLE CATEGORIES

SELECT NAME,COUNT(DISTINCT CATEGORY) AS NO_OF_CATEGORIES
FROM ZEPTO
GROUP BY NAME
HAVING COUNT(DISTINCT CATEGORY)>1
ORDER BY NO_OF_CATEGORIES DESC

--Q6.FINDING DUPLICATE CATEGORY+PRODUCT COMBINATION

SELECT CATEGORY,NAME,COUNT(*) AS [COUNT]
FROM ZEPTO
GROUP BY CATEGORY,NAME
HAVING COUNT(*)>1
ORDER BY [COUNT] DESC

--Q7.CHECKING COMPLETE DUPLICATE ROWS

SELECT CATEGORY,NAME,MRP,
DISCOUNTPERCENT,AVAILABLEQUANTITY,DISCOUNTEDSELLINGPRICE,
WEIGHTINGMS,OUTOFSTOCK,QUANTITY,COUNT(*) AS [COUNT]
FROM ZEPTO
GROUP BY CATEGORY,NAME,MRP,
DISCOUNTPERCENT,AVAILABLEQUANTITY,DISCOUNTEDSELLINGPRICE,
WEIGHTINGMS,OUTOFSTOCK,QUANTITY
HAVING COUNT(*)>1

--Q8.REMOVING DUPLICATES

WITH DUPLICATE_ROWS AS (
SELECT *,ROW_NUMBER() OVER (PARTITION BY
CATEGORY,NAME,MRP,
DISCOUNTPERCENT,AVAILABLEQUANTITY,DISCOUNTEDSELLINGPRICE,
WEIGHTINGMS,OUTOFSTOCK,QUANTITY
ORDER BY SKU_ID) AS RN
FROM ZEPTO
)
DELETE FROM DUPLICATE_ROWS WHERE RN>1

--Q9.CHECKING NEGATIVE VALUES

SELECT * FROM ZEPTO
WHERE MRP<0
OR
discountedSellingPrice<0
OR
availableQuantity<0
OR
discountedSellingPrice<0
OR
weightInGms<0
OR
outOfStock<0
OR
quantity<0

--Q11.CHECKING PRODUCTS HAVING ZERO QUANTITY

SELECT *
FROM ZEPTO
WHERE QUANTITY = 0

--Q12.PRODUCTS HAVING ZERO WEIGHT

SELECT * FROM ZEPTO
WHERE WEIGHTINGMS=0

--Q13.CHECKING OUT-OF-STOCK PRODUCTS

SELECT * FROM ZEPTO
WHERE OUTOFSTOCK=1

--Q14.CHECKING AVAILABLE PRODUCTS

SELECT * FROM ZEPTO
WHERE OUTOFSTOCK=0